### PR TITLE
Network graph, computer info and new layout

### PR DESCRIPTION
**Pull request by pescuma**
I've created these to use with machines in a datacenter, and I think they may be useful for other people.

There are also a few changes to fix git issues that were happening in my machine.

### CODE REVIEW

**Comment by MarcoPixel** [comment]
Thanks for contributing! :)

I will probably check it out on this weekend and will report back here 👍

**Comment by pescuma** [comment]
@MarcoPixel  updated to reflect your latest changes

**Comment by pescuma** [comment]
@MarcoPixel Done. Sorry for the delay.

**Comment by MarcoPixel** [comment]
Looks good 👍

**Pull request merged**
